name: Deprecated Routes

on: workflow_dispatch

jobs:
  build-and-test:
    env:
      INTEGRATION_TESTS_PROJECT: 'src/EVEClient.NET.IntegrationTests/EVEClient.NET.IntegrationTests.csproj'
      REFRESH_TOKEN: ${{ secrets.ESI_SSO_REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.ESI_CLIENT_ID }}
      
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Test
      run: dotnet test $INTEGRATION_TESTS_PROJECT --filter "Category=SmokeTest" --environment ESI_REFRESH_TOKEN=$REFRESH_TOKEN --environment ESI_CLIENT_ID=$CLIENT_ID -- NUnit.TestOutputXml=TestResults
    
    - name: NUnit Tests Report
      uses: daazarov/NUnitTestResultSummary@v1
      with:
        filename: src/EVEClient.NET.IntegrationTests/bin/Debug/net7.0/TestResults/EVEClient.NET.IntegrationTests.xml
        badge: true
        format: markdown
        output: file
        passed: true
        
    - name: Commit Tests Results
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Add/Replace NUnit results'
        add: 'nunit-testresult-summary.md --force'
